from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from database import engine, get_db
import models, schemas

# 1. Create Tables
# This tells SQLAlchemy to create the tables in the DB if they don't exist.
models.Base.metadata.create_all(bind=engine)

app = FastAPI()

# This tells the browser: "It's okay for other websites to talk to me."
origins = [
    "http://localhost",
    "http://localhost:8000",
    "http://localhost:5500", # We will run our frontend here
    "http://127.0.0.1:5500",
    "*" # In production, never use *. But for learning, this allows ANY connection.
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.post("/users/", response_model=schemas.UserResponse)
def create_user(user: schemas.UserCreate, db: Session = Depends(get_db)):
    # Check if user already exists
    db_user = db.query(models.User).filter(models.User.username == user.username).first()
    if db_user:
        raise HTTPException(status_code=400, detail="Username already registered")

    # Create new user object
    new_user = models.User(username=user.username, password=user.password, balance=0)

    # Add to DB and Commit
    db.add(new_user)
    db.commit()

    # Refresh to get the ID generated by the DB
    db.refresh(new_user)
    return new_user

# 1. Get User Balance
@app.get("/users/{user_id}", response_model=schemas.UserResponse)
def read_user(user_id: int, db: Session = Depends(get_db)):
    # Query: SELECT * FROM users WHERE id = user_id
    db_user = db.query(models.User).filter(models.User.id == user_id).first()
    
    # Error Handling: 404 Not Found
    if db_user is None:
        raise HTTPException(status_code=404, detail="User not found")
    return db_user


# 2. Deposit Money
@app.post("/users/{user_id}/deposit", response_model=schemas.UserResponse)
def deposit_money(user_id: int, transaction: schemas.Transaction, db: Session = Depends(get_db)):
    db_user = db.query(models.User).filter(models.User.id == user_id).first()
    if db_user is None:
        raise HTTPException(status_code=404, detail="User not found")
    
    # Logic: Add amount
    db_user.balance += transaction.amount
    
    # Save Logic
    db.commit()
    db.refresh(db_user) # Reload from DB to get updated state
    return db_user


# 3. Withdraw Money
@app.post("/users/{user_id}/withdraw", response_model=schemas.UserResponse)
def withdraw_money(user_id: int, transaction: schemas.Transaction, db: Session = Depends(get_db)):
    db_user = db.query(models.User).filter(models.User.id == user_id).first()
    if db_user is None:
        raise HTTPException(status_code=404, detail="User not found")
        
    # Logic: Check funds
    if db_user.balance < transaction.amount:
        raise HTTPException(status_code=400, detail="Insufficient funds")
    
    # Logic: Subtract amount
    db_user.balance -= transaction.amount
    
    db.commit()
    db.refresh(db_user)
    return db_user